#!/usr/bin/env bash

cd `dirname $0`
cd ..

echo "================================ Build Dap.Platform"
cd src/Dap.Platform
dotnet build -c Release
cd ../../

echo "" && \
dotnet fsi prepare-demo.fsx

