#!/usr/bin/env bash

cd `dirname $0`
cd ..

echo "================================ Build Dap.Context" && \
fake build -t Dap.Context:Build -s && \
echo "================================ Prepare Fable.Dap.Platform" && \
fsharpi prepare-platform.fable.fsx && \
echo "================================ Prepare Dap.Platform (Stage 1)" && \
fsharpi prepare-platform.fsx && \
echo "================================ Build Dap.Platform" && \
fake build -t Dap.Platform:Build -s && \
echo "================================ Prepare Dap.Platform (Stage 2)" && \
fsharpi prepare-platform-packs.fsx && \
echo "================================ Prepare Dap.WebSocket" && \
fsharpi prepare-websocket.fsx && \
echo "================================ Prepare Dap.Archive" && \
fsharpi prepare-archive.fsx
