#!/usr/bin/env bash

cd `dirname $0`
cd ..

fake build -t Dap.Prelude:build -s && \
fake build -t Dap.Context:build -s && \
fake build -t Dap.Platform:build -s && \
echo "" && \
fsharpi prepare-demo.fsx

