#!/usr/bin/env bash

cd `dirname $0`
cd ..

echo "================================ Build Dap.Platform"
cd src/Dap.Platform
dotnet build -c Release
cd ../../

echo "================================ Prepare Dap.Platform (Stage 1)" && \
dotnet fsi prepare-platform.fsx && \
echo "================================ Prepare Dap.Platform (Stage 2)" && \
dotnet fsi prepare-platform-packs.fsx && \
echo "================================ Prepare Dap.WebSocket" && \
dotnet fsi prepare-websocket.fsx && \
echo "================================ Prepare Dap.Archive" && \
dotnet fsi prepare-archive.fsx
